### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by mn265** [suryasundarraj/pubnub-esp8266-rest-api#2]
Arduino: 1.8.1 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

C:\Users\Mohit\Documents\Arduino\PUBNUB_SUB\PUBNUB_SUB.ino: In function 'uint8_t json_handler(String)':

PUBNUB_SUB:97: error: return-statement with no value, in function returning 'uint8_t {aka unsigned char}' [-fpermissive]

     return;

     ^

exit status 1
return-statement with no value, in function returning 'uint8_t {aka unsigned char}' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by suryasundarraj** [comment]
Resolved the issue. Use {} enclosed data, as the messages.
Avoid sending the string directly it will get into parseObjectFailure.

**Comment by mn265** [comment]
thanks for reply.i will try and update you..thank you so much for this nice
tutorial ...
